
/*
SET OPERATORE:
	SET OPERATORS IN SQL COMBINE THE RESULTS OF MULTIPLE QUERIES INTO A SINGLE RESULT SET
	

	RULES:
	#1. 
		SET OPERATORS CAN BE USED ALMOST IN ALL CLAUSES WHERE|JOIN|GROUP BY|HAVING
		ORDER BY IS ALLOWED ONLY ONCE AT THE END OF QUERY
	#2.
		NUMBER OF COLUMNS OF EACH QUERY MUST BE SAME

	#3.
		DATATYPES OF COLUMNS IN EACH QUERY MUST BE COMPATIBLE

	#4. 
		ORDER OF COLUMNS MUST BE SAME

	#5.
		THE COLUMN NAMES IN THE RESULT SET ARE DETARMINED BY THE COLUMN NAMES SPECIFIED IN THE FIRST QUERY

	#6.
		EVEN IF ALL REULES ARE MEET AND SQL SHOWS NO ERRORS, THE RESULT MAY BE INCORRECT
		INCORRECT COLUMN SALACTION LEADS TO INACCURATE RESULTS
*/
--#1
	SELECT
	FIRSTNAME,
	LASTNAME
	FROM Sales.Customers
	UNION
	SELECT
	FIRSTNAME,
	LASTNAME
	FROM Sales.Employees;

	--#2
	SELECT
	CUSTOMERID, --Conversion failed when converting the varchar value 'Frank' to data type int.
	LASTNAME
	FROM Sales.Customers
	UNION
	SELECT
	FIRSTNAME,
	LASTNAME
	FROM Sales.Employees;

	--#3
	SELECT
	FIRSTNAME,
	LASTNAME
	FROM Sales.Customers
	UNION
	SELECT
	LASTNAME,
	FIRSTNAME
	FROM Sales.Employees;

	--#4
	SELECT
	CUSTOMERID, --INT.
	LASTNAME
	FROM Sales.Customers
	UNION
	SELECT
	LASTNAME, --VARCHAR
	EMPLOYEEID
	FROM Sales.Employees;

	--#5
	SELECT
	FIRSTNAME FIRST_NAME,
	LASTNAME LAST_NAME
	FROM Sales.Customers
	UNION
	SELECT
	FIRSTNAME,
	LASTNAME
	FROM Sales.Employees;

	--#6
	SELECT
	FIRSTNAME,
	LASTNAME
	FROM Sales.Customers
	UNION
	SELECT
	LASTNAME,
	FIRSTNAME
	FROM Sales.Employees;

	-- UNION
	-- RETURNS ALL THE DISTINCT ROWS FROM BOTH QUERIES
	-- REMOVE ALL DUPLICATES ROWS FROM THE RESULT