-- Find the total Sales across all orders

Use salesDb;

SELECT * FROM SALES.Orders;

select sum(sales) as total_sales from sales.Orders;

-- Find total sales for each product
select productID, sum(sales) Total_sales from sales.orders
group by ProductID;

/*
Find the total sales for each product
Additionally provide details such orderID, order Date
*//*
SELECT
	ORDERID, ORDERDATE, PRODUCTID, SUM(SALES) AS TOTAL_SALES FROM SALES.Orders
	GROUP BY ORDERID, ORDERDATE, PRODUCTID;
	*/
	SELECT 
		ORDERID, 
		ORDERDATE, 
		PRODUCTID,
		SUM(SALES) OVER(PARTITION BY PRODUCTID) AS TOTALSALESPRODUCTS
	FROM SALES.Orders;

/*
Window Functions/Analytical Functions
Syntax:
********
Window Function() over(partition order by frame)
Eg:
AVG(salary) OVER(PARTITION BY CATAGORY ORDER BY ORDERDATE ROWS UNBUNDED PRECEDING)
	EMPLY : RANK() OVER(ORDER BY ORDERDATE)
	COLUMN : AVG(SAL) OVER(ORDER BY ORDERDATE)
	NUMBER : NTEIL(2) OVER(ORDER BY ORDERDATE)
	MULTIPLE ARGUMENTS : LEAD(SALES,2,10) OVER(ORDER BY ORDERDATE)
	CONDITIONAL LOGIN : SUM(CASE WHEN SALES>100 THEN 1 ELES 0) OVER(ORDER BY ORDERDATE)

	WINDOW FUNCTIONS:
	AGGREGRATE FUNCTIONS:
		SUM()	NUMERIC DATATYPE
		MIN()	NUMERIC DATATYPE
		MAX()	NUMERIC DATATYPE
		AVG()	NUMERIC DATATYPE
		COUNT() ALL
	RANK FUNCTIONS:
		RANK()	EMPTY
		ROW_NUMBER()	EMPTY
		DENSE_RANK()	EMPTY
		CUME_DIST()		EMPTY
		PERCENT_RANK()	EMPTY
		NTILE(N)	NUMERIC DATATYPE
	VALUE(ANALYTICAL FUNCTIONS)
		LEAD()	ALL
		LAG()	ALL
		FIRST_VALUE()	ALL


	ORDER BY:
	PARTATION CLAUES IS OPTIONAL FOR ALL WINDOW FUNCTIONS
	ORDER BY IS OPTIONAL FOR AGGREGRATE FUNCTIONS, REQUIRED FOR RANK FUNCTIONS AND VALUE(ANALYTICAL FUNCTIONS)



	FRAME CLAUSE:
	AVG(SALES) OVER(PARTATION BY CATAGORY ORDER BY ORDERDATE
					ROWS BETWEEN CURRENT ROW AND UNBOUNDED PRECEDING)
			ROWS:
				FRAME TYPES:
					ROWS
					RANGE
			CURRENT ROW:
				FRAME BOUNDARY(LOWER VALUE)
					CURRENT ROW
					N PRECEDING
					UNBOUNDED PRECEDING
			UNBOUNDED PRECEDING
				FRAME BOUNDARY(HIGHER VALUE)
					CURRENT ROW
					N FOLLOWING
					UNBOUNDED FOLLOWING
	RULES:
	FRAME CLAUSE CAN BE ONLY USED WITH ORDER BY CLAUES
	LOWER VALUE MUST BE BEFORE HIGHER VALUE
	

*/

-- FIND THE TOTAL SALES FOR EACH PRODUCT
-- ADDTIONALLY PROVIDE DETAILS SUCH ORDERID, ORDERDATE
SELECT
	ORDERID,
	ORDERDATE,
	SUM(SALES) OVER() AS TOTALSALES
	FROM SALESDB.SALES.Orders;

SELECT
	ORDERID,
	ORDERDATE,
	PRODUCTID,
	SALES,
	SUM(SALES) OVER() AS SUMOFSALES,
	SUM(SALES) OVER(PARTITION BY PRODUCTID) AS TOTALSALES
	FROM SaleSDB.Sales.Orders;

-- FIND THE TOTAL SALES ACROSS ALL ORDERS
-- FIND THE TOTAL SALES FOR EACH PRODUCT
-- FIND THE TOTAL SALES FOR EACH COMBINATION OF PRODUCT AND ORDER STATUS
-- ADDTIONALLY PROVIDE DETAILS SUCH ORDERID, ORDERDATE
SELECT
	ORDERID,
	ORDERDATE,
	PRODUCTID,
	ORDERSTATUS,
	SUM(SALES) OVER() TOTAL,
	SUM(SALES) OVER(PARTITION BY PRODUCTID) AS TOTALSALES,
	SUM(SALES) OVER(PARTITION BY PRODUCTID, ORDERSTATUS) AS SALESPRODUCTS
	FROM SalesDB.Sales.Orders;
	
-- RANK EACH ORDER BASED ON THEIR SALES FROM HEIGHEST TO LOWEST
-- ADDITIONALLY PROVIDE DETAILS SUCH ORDERID, ORDERDATE
SELECT 
	ORDERID,
	ORDERDATE,
	SALES,
	RANK() OVER(ORDER BY SALES DESC) AS SALESORDER
	FROM SalesDB.Sales.Orders;

SELECT
	ORDERID,
		ORDERDATE,
		ORDERSTATUS,
		SALES,
		SUM(SALES) OVER(PARTITION BY ORDERSTATUS ORDER BY ORDERDATE
			ROWS BETWEEN CURRENT ROW AND 2 FOLLOWING) AS SALESSUM
			FROM SalesDB.Sales.Orders;

-- FOR QUICK RESULTS WE MAY USE ONLY PRECEDING, FOLLOWING WILL NOT NOT RETRIVE THE DATA.
SELECT
	ORDERID,
	ORDERDATE,
	ORDERSTATUS,
	SALES,
	SUM(SALES) OVER(PARTITION BY ORDERSTATUS ORDER BY ORDERDATE
					ROWS UNBOUNDED PRECEDING) AS SALESSUM
					FROM SalesDB.Sales.Orders;

-- DEFAULT FRAME
SELECT
	ORDERID,
	ORDERDATE,
	ORDERSTATUS,
	SALES,
	SUM(SALES) OVER(PARTITION BY ORDERSTATUS ORDER BY ORDERDATE--) AS SALESSUM
	ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS SALESSUM -- IT IS THE DEAFULT INNER QUERY
	FROM SalesDB.Sales.Orders;

	-- WE CAN USE WINDOW FUNCTIONS IN SELECT CLAUSE OR ORDER BY CLAUES
	SELECT
		ORDERID,
		ORDERDATE,
		ORDERSTATUS,
		SALES,
		SUM(SALES) OVER(PARTITION BY ORDERSTATUS) AS TOTALSALES
		FROM SalesDB.Sales.Orders
		ORDER BY
		SUM(SALES) OVER(PARTITION BY ORDERSTATUS) DESC;

	-- NESTING WINDOW FUNCTIONS ARE NOT ALLOWED
	SELECT
		ORDERID,
		ORDERDATE,
		ORDERSTATUS,
		SALES,
		SUM(SUM(SALES) OVER(PARTITION BY ORDERSTATUS)) OVER(PARTITION BY ORDERSTATUS) AS TOTALSALES -- NOT ALLOWED
		FROM SalesDB.Sales.Orders --Windowed functions cannot be used in the context of another windowed function or aggregate.
		ORDER BY
		SUM(SALES) OVER(PARTITION BY ORDERSTATUS) DESC;

	-- SQL EXECUTE WINDOW FUNCTION AFTER WHERE CLAUE
		-- FIND THE TOTAL SALES FOR EACH ORDER STATUS
		-- ONLY FOR TWO PRODUCTS 101 AND 102
	SELECT
		ORDERID,
		PRODUCTID,
		ORDERDATE,
		ORDERSTATUS,
		SALES,
		SUM(SALES) OVER(PARTITION BY ORDERSTATUS) AS TOTALSALES
		FROM SalesDB.Sales.Orders
		WHERE PRODUCTID IN (101, 102)
		ORDER BY ProductID;

	-- WINDOW FUNCTION CAN BE USED TOGETHER WITH GROUP BY CLAUSE
	-- IN THE SAME QUERY, ONLY IF THE SAME COLUMNS ARE USED

		-- RANK CUSTOMERS BASED ON THEIR TOTAL SALES
	SELECT
		CUSTOMERID,
		SUM(SALES) AS SALESSUM,
		RANK() OVER(ORDER BY SUM(SALES) DESC) AS RANKCUSTOMERS
		FROM SalesDB.Sales.Orders
		GROUP BY CustomerID;

/*
 AGGREGATE FUNCTIONS:
 SUM(SALES) OVER(PARTITION BY PRODUCTID ORDER BY SALES)
 SUM(SALES) -> SALES SHOULD BE INT DATATYPE
 PARTITION BY -> OPTIONAL
 ORDER BY -> OPTIONAL

 COUNT()
 SUM()
 MIN()
 MAX()
 AVG()

 OVERALL ANALYSIS
 CATAGORY ANALYSIS
 QUALITY CHECKS: IDENTIFY NULLS
 QUALITY CHECK: IDENTIFY DUPLICATES

 */
 --COUNT():
--	RETURN THE NUMBER OF ROWS WITHIN A WINDOW
	-- FIND THE TOTAL NUMBER OF ORDERS
	SELECT 
		COUNT(*) TOTALORDERS --OVERAL ANALYSIS
		FROM SALESDB.SALES.ORDERS;

	--PROVIDE DETAILS SUCH ORDERID,ORDERDATE
	SELECT 
		ORDERID,
		ORDERDATE,
		COUNT(*) OVER() TOTALORDERS
		FROM SalesDB.Sales.Orders;

	-- FIND TOTAL NUMBER OF ORDERS FOR EACH CUSTOMERS
	SELECT
		ORDERID,
		CustomerID,
		ORDERDATE,
		COUNT(*) OVER() TOALORDERS,
		COUNT(*) OVER(PARTITION BY CUSTOMERID) ORDERBYCUSTOMERS
		FROM SalesDB.Sales.Orders;

		-- FIND THE TOTAL NUMBER OF CUSTOMERS
		-- PROVIDE ALL CUSTOMER DETAILS
	SELECT
		*,COUNT(*) OVER() TOTALCUSTOMERS
		FROM SALESDB.SALES.CUSTOMERS;

		-- TOTAL NUMBER OF SCORES FOR THE CUSTOMERS
	SELECT 
	*,
	COUNT(*) OVER() TOTALCUSTOMERS,
	--COUNT(1) OVER() TOTALCUSTOMERS,
	COUNT(SCORE) OVER() TOTALSCORE,
	COUNT(COUNTRY) OVER() TOTALCOUNTRIES
	FROM SalesDB.Sales.Customers;

	-- DATA QUALITY ISSUES 
	--DUPLICATE DATA LEADS TO INACCURACIES IN ANALYSIS COUNT() CAN BE USED TO IDENTIFY DUPLICATES

	-- CHECK WHETHER THE TABLE 'ORDERS' CONTAINS ANY DUPLICATE ROWS
	SELECT 
		ORDERID,
		COUNT(*) OVER(PARTITION BY ORDERID) AS DUPLICATES
		FROM SalesDB.Sales.Orders;

	SELECT
		ORDERID,
		COUNT(*) OVER(PARTITION BY ORDERID) AS DUPLICATES
		FROM SalesDB.Sales.OrdersArchive;

	SELECT
	*
	FROM (
		SELECT
			ORDERID,
			COUNT(*) OVER(PARTITION BY ORDERID) AS DUPLICATES
			FROM SalesDB.Sales.OrdersArchive) T WHERE DUPLICATES>1;

	/*
	SUM():
		RETURNS SUM OF ALL VALUES WITHIN A WINDOW
	*/
	SELECT
		ORDERID,
		SALES,
		PRODUCTID,
		SUM(SALES) OVER() TOTALSALES,
		SUM(SALES) OVER(PARTITION BY PRODUCTID) SALESBYPRODUCT
		FROM SalesDB.Sales.Orders;
	
	-- FIND THE PERCENTAGE CONTRIBUTION OF EACH PRODUCT'S SALES TO THE SALES
	SELECT
		ORDERID,
		PRODUCTID,
		SALES,
		SUM(SALES) OVER() SUMOFSALES,
		ROUND(CAST(SALES AS FLOAT)/SUM(SALES) OVER() * 100,2) AS PERCENTAGE --PART TO WHOLE ANALYSIS
		FROM SalesDB.Sales.Orders;


	/*
	AVG():
		RETURNS THE AVERAGE VALUES OF EACH WINDOW
	*/
	-- FIND THE AVG SALES ACROSS ALL ORDERS AND THE AVG SALES FOR EACH PRODUCT
	-- PROVIDE DETAILS SUCH AS ORDERID, ORDERDATE.
	SELECT
		ORDERID,
		ORDERDATE,
		SALES,
		AVG(SALES) OVER() AVGSALES,
		ProductID,
		AVG(SALES) OVER(PARTITION BY PRODUCTID) AS AVGPRODUCT
		FROM SalesDB.Sales.Orders;

	-- FIND THE AVG SCORE OF CUSTOMERS
	-- PROVIDE DETAILS SUCH AS CUSTOMERID AND LASTNAME
	SELECT
		CUSTOMERID,
		LASTNAME,
		SCORE,
		COALESCE(SCORE,0) CUSTOMERSCORE,
		AVG(SCORE) OVER() AVGWITHNULLS,
		AVG(COALESCE(SCORE,0)) OVER() AS AVGWITHOUTNULL
		FROM SalesDB.Sales.Customers;

	--FIND ALL ORDERS WHERE SALES ARE HIGHER THAN THE AVERAGE SALES ACROSS ALL ORDERS
	SELECT * FROM (SELECT
		ORDERID,
		PRODUCTID,
		SALES,
		AVG(SALES) OVER() AVGSALES
		FROM SalesDB.Sales.Orders)T
		WHERE SALES>AVGSALES;

